name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build (skip if no build step)
        run: |
          # add build commands here if needed
          echo "No build step configured"
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
